basePath: /api/v1/
definitions:
  dto.AdminUserRequest:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
    type: object
  dto.JobPostingListResponse:
    properties:
      item:
        items:
          $ref: '#/definitions/dto.JobPostingResponse'
        type: array
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
    type: object
  dto.JobPostingRequest:
    properties:
      Department:
        type: string
      description:
        type: string
      location:
        type: string
      position_type:
        type: string
      title:
        type: string
    type: object
  dto.JobPostingResponse:
    properties:
      application_count:
        type: integer
      createdAt:
        type: string
      department:
        type: string
      description:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      location:
        type: string
      position_type:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 뽑기팡 Spine 애플리케이션
  title: 뽑기팡 API
  version: 0.0.1
paths:
  /auth/create-admin-user:
    post:
      description: 관리자 어드민 계정 생성 API
      parameters:
      - description: 어드민 생성 요청
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.AdminUserRequest'
      responses: {}
      summary: (관리자) 어드민 계정 생성
      tags:
      - Auth
  /careers/job-postings:
    get:
      description: 공고 목록을 활성화 상태, 페이지네이션 QueryString 옵션으로 가져옵니다.
      parameters:
      - description: 공고 활성화 상태
        in: query
        name: isActive
        type: boolean
      - description: 요청 페이지 번호
        in: query
        name: page
        required: true
        type: integer
      - description: 한번에 받을 페이지의 사이즈
        in: query
        name: size
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.JobPostingListResponse'
      summary: (공통) 모집 공고 목록 조회
      tags:
      - Careers
    post:
      consumes:
      - application/json
      description: 관리자 모집 공고 생성 API
      parameters:
      - description: 요청 Body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.JobPostingRequest'
      produces:
      - application/json
      responses: {}
      summary: (관리자) 모집 공고 생성
      tags:
      - Careers
  /careers/job-postings/{id}:
    get:
      description: 사용자 모집 공고 상세 조회 API
      parameters:
      - description: 요청 공고
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: (사용자) 모집 공고 상세 조회
      tags:
      - Careers
swagger: "2.0"
